[project]
name = "simple-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastembed>=0.7.0",
    "ipykernel>=6.29.5",
    "numpy>=2.2.6",
    "ollama>=0.4.8",
    "qdrant-client>=1.14.2",
    "tqdm>=4.67.1",
]
